### ISSUE TITLE
Frontend HTML from VScode extension is not rendered

### ISSUE THREAD

**Issue by mathis-girault** [eclipsesource/ide-ai-assistant#33]
Setup:
- Any working Webview View Vscode extension, for example [ours](https://github.com/eclipsesource/ide-ai-assistant/tree/feature/ui-template) or a [vscode sample one](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample).
- Opening the extension within theia, either as a `.vsix` file, or when build and symlinked into the plugins/ folder.

Issue:
Then, the extension does exist inside theia and can be opened, but there is nothing rendered, cf image below.
![image](https://github.com/eclipsesource/ide-ai-assistant/assets/74116752/dada463d-403b-431d-aa37-53ff1fbcb438)

Theia dependencies are all set to `latest` (ran on the 24/11/2023).
The extensions mentioned beforehand have been both tested inside vscode (both as `.vsix` file and build), and work perfectly.

**Comment by kavitha-subr** [comment]
By default, the extension is activated on the first usage of a command. To override this, an activation event can be specified in package.json
