### ISSUE TITLE
As a project lead, I want to utilize the AI Assistant to update a project's readme file.

### ISSUE THREAD

**Issue by mathis-girault** [eclipsesource/ide-ai-assistant#43]
As a logged-in project lead, I navigate to the messages section for the specific project.
Upon reaching messages, I can request the AI Assistant for updating the project's readme file.
If the amount of messages surpasses a limit, I can choose only a relevant subset of these messages.
Finally, the readme file will be automatically updated, letting me then room for reviewing and modifying the contents to my satisfaction.

**Comment by JonasHelming** [comment]
Sounds OK.
